version: '3'

services:

  back:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./back/:/home/node/app
    expose:
      - "3000"
    ports:
      - '3000:3000'
    command: "npm start"
    depends_on:
    - mongo

  front:
    build: ./front/
    working_dir: /opt/app
    volumes:
    - ./front/:/opt/app
    ports:
    - '4200:4200'
    depends_on:
    - mongo

  mongo:
    image: mongo
    restart: always
    ports:
    - '27017:27017'
